ERROR - 2024-01-28 19:47:06 --> Table 'dbpena.log' doesn't exist
CRITICAL - 2024-01-28 19:47:06 --> Call to a member function getResult() on bool
#0 C:\xampp\htdocs\pena\app\Controllers\Home.php(838): App\Models\M_model->join_w('log', 'user', 'log.id_user=use...', Array)
#1 C:\xampp\htdocs\pena\system\CodeIgniter.php(832): App\Controllers\Home->log()
#2 C:\xampp\htdocs\pena\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#3 C:\xampp\htdocs\pena\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\pena\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\pena\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#6 {main}
ERROR - 2024-01-28 20:46:10 --> Unknown column 'penguna.created_at' in 'order clause'
CRITICAL - 2024-01-28 20:46:10 --> Call to a member function getResult() on bool
#0 C:\xampp\htdocs\pena\app\Controllers\Home.php(66): App\Models\M_model->join2('penguna', 'user', 'penguna.user=us...')
#1 C:\xampp\htdocs\pena\system\CodeIgniter.php(832): App\Controllers\Home->penguna()
#2 C:\xampp\htdocs\pena\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#3 C:\xampp\htdocs\pena\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\pena\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\pena\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2024-01-28 20:50:35 --> Invalid file: tambah_penguna.php
#0 C:\xampp\htdocs\pena\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('tambah_penguna....')
#1 C:\xampp\htdocs\pena\system\Common.php(1089): CodeIgniter\View\View->render('tambah_penguna', Array, true)
#2 C:\xampp\htdocs\pena\app\Controllers\Home.php(104): view('tambah_penguna', Array)
#3 C:\xampp\htdocs\pena\system\CodeIgniter.php(832): App\Controllers\Home->tambah_penguna()
#4 C:\xampp\htdocs\pena\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\pena\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\pena\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\pena\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#8 {main}
ERROR - 2024-01-28 20:52:43 --> Table 'dbpena.log' doesn't exist
ERROR - 2024-01-28 20:56:58 --> Table 'dbpena.log' doesn't exist
ERROR - 2024-01-28 20:58:38 --> Table 'dbpena.log' doesn't exist
ERROR - 2024-01-28 22:58:08 --> Table 'dbpena.user' doesn't exist in engine
CRITICAL - 2024-01-28 22:58:08 --> Call to a member function getRowArray() on bool
#0 C:\xampp\htdocs\pena\app\Controllers\Home.php(50): App\Models\M_model->getWhere2('user', Array)
#1 C:\xampp\htdocs\pena\system\CodeIgniter.php(832): App\Controllers\Home->aksi_login()
#2 C:\xampp\htdocs\pena\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#3 C:\xampp\htdocs\pena\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\pena\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\pena\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#6 {main}
ERROR - 2024-01-28 22:58:42 --> Table 'dbpena.user' doesn't exist in engine
CRITICAL - 2024-01-28 22:58:42 --> Call to a member function getRowArray() on bool
#0 C:\xampp\htdocs\pena\app\Controllers\Home.php(50): App\Models\M_model->getWhere2('user', Array)
#1 C:\xampp\htdocs\pena\system\CodeIgniter.php(832): App\Controllers\Home->aksi_login()
#2 C:\xampp\htdocs\pena\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#3 C:\xampp\htdocs\pena\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\pena\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\pena\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#6 {main}
ERROR - 2024-01-28 22:58:49 --> Table 'dbpena.user' doesn't exist in engine
CRITICAL - 2024-01-28 22:58:49 --> Call to a member function getRowArray() on bool
#0 C:\xampp\htdocs\pena\app\Controllers\Home.php(50): App\Models\M_model->getWhere2('user', Array)
#1 C:\xampp\htdocs\pena\system\CodeIgniter.php(832): App\Controllers\Home->aksi_login()
#2 C:\xampp\htdocs\pena\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#3 C:\xampp\htdocs\pena\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\pena\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\pena\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#6 {main}
ERROR - 2024-01-28 22:59:01 --> Table 'dbpena.user' doesn't exist in engine
CRITICAL - 2024-01-28 22:59:01 --> Call to a member function getRowArray() on bool
#0 C:\xampp\htdocs\pena\app\Controllers\Home.php(50): App\Models\M_model->getWhere2('user', Array)
#1 C:\xampp\htdocs\pena\system\CodeIgniter.php(832): App\Controllers\Home->aksi_login()
#2 C:\xampp\htdocs\pena\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#3 C:\xampp\htdocs\pena\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\pena\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\pena\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#6 {main}
ERROR - 2024-01-28 23:01:07 --> Error connecting to the database: No connection could be made because the target machine actively refused it.

CRITICAL - 2024-01-28 23:01:07 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it.

#0 C:\xampp\htdocs\pena\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\pena\system\Database\BaseBuilder.php(1588): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\pena\app\Models\M_model.php(41): CodeIgniter\Database\BaseBuilder->getWhere(Array)
#3 C:\xampp\htdocs\pena\app\Controllers\Home.php(50): App\Models\M_model->getWhere2('user', Array)
#4 C:\xampp\htdocs\pena\system\CodeIgniter.php(832): App\Controllers\Home->aksi_login()
#5 C:\xampp\htdocs\pena\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 C:\xampp\htdocs\pena\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\pena\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\pena\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#9 {main}
ERROR - 2024-01-28 23:06:19 --> Table 'dbpena.user' doesn't exist in engine
CRITICAL - 2024-01-28 23:06:19 --> Call to a member function getRowArray() on bool
#0 C:\xampp\htdocs\pena\app\Controllers\Home.php(50): App\Models\M_model->getWhere2('user', Array)
#1 C:\xampp\htdocs\pena\system\CodeIgniter.php(832): App\Controllers\Home->aksi_login()
#2 C:\xampp\htdocs\pena\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#3 C:\xampp\htdocs\pena\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\pena\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\pena\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#6 {main}
ERROR - 2024-01-28 23:06:30 --> Table 'dbpena.user' doesn't exist in engine
CRITICAL - 2024-01-28 23:06:30 --> Call to a member function getRowArray() on bool
#0 C:\xampp\htdocs\pena\app\Controllers\Home.php(50): App\Models\M_model->getWhere2('user', Array)
#1 C:\xampp\htdocs\pena\system\CodeIgniter.php(832): App\Controllers\Home->aksi_login()
#2 C:\xampp\htdocs\pena\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#3 C:\xampp\htdocs\pena\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\pena\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\pena\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#6 {main}
